import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { LogOut, Package, Store, UserRound } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { money } from "@/components/storefront/catalog";

export const Route=createFileRoute("/_authenticated/account")({head:()=>({meta:[{title:"حسابي — TURBO"},{name:"description",content:"تابع طلباتك وبيانات حساب TURBO."},{property:"og:title",content:"حسابي في TURBO"},{property:"og:description",content:"طلباتك وبياناتك في مكان واحد."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"},{name:"robots",content:"noindex"}]}),component:Page});
function Page(){const {user}=Route.useRouteContext();const navigate=useNavigate();const {data:orders=[]}=useQuery({queryKey:["my-orders",user.id],queryFn:async()=>{const {data,error}=await supabase.from("orders").select("id,order_number,grand_total,fulfillment_status,created_at").eq("user_id",user.id).order("created_at",{ascending:false});if(error)throw error;return data??[]}});const signOut=async()=>{await supabase.auth.signOut();navigate({to:"/"})};return <div className="turbo-container section-space min-h-[60vh]"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-bold text-primary">MY TURBO</p><h1 className="mt-2 text-4xl font-bold md:text-6xl">حسابي</h1><p dir="ltr" className="mt-3 text-start text-sm text-muted-foreground">{user.email}</p></div><Button variant="outline" onClick={signOut}><LogOut/> تسجيل الخروج</Button></div><div className="mt-10 grid gap-4 sm:grid-cols-3"><div className="rounded-[10px] border bg-card p-5"><UserRound className="text-primary"/><h2 className="mt-4 font-bold">بيانات الحساب</h2></div><Link to="/wholesale-apply" className="rounded-[10px] border bg-card p-5"><Store className="text-primary"/><h2 className="mt-4 font-bold">طلب تاجر جملة</h2></Link><div className="rounded-[10px] border bg-card p-5"><Package className="text-primary"/><h2 className="mt-4 font-bold">طلباتي</h2><p className="mt-1 text-sm text-muted-foreground">{orders.length} طلب</p></div></div><section className="mt-12"><h2 className="text-2xl font-bold">الطلبات</h2>{orders.length?<div className="mt-5 grid gap-3">{orders.map(o=><div key={o.id} className="flex flex-wrap justify-between gap-4 rounded-[10px] border bg-card p-5"><div><strong dir="ltr">#{o.order_number}</strong><p className="mt-1 text-sm text-muted-foreground">{new Date(o.created_at).toLocaleDateString("ar-EG")}</p></div><div className="text-end"><strong>{money(o.grand_total)}</strong><p className="mt-1 text-sm text-primary">{statusLabel[o.fulfillment_status]}</p></div></div>)}</div>:<p className="mt-5 rounded-[10px] border border-dashed p-8 text-center text-muted-foreground">مفيش طلبات لسه.</p>}</section></div>}
const statusLabel={pending:"قيد المراجعة",confirmed:"تم التأكيد",processing:"قيد التجهيز",shipped:"خرج للتوصيل",delivered:"تم التوصيل",cancelled:"ملغي"} as const;