import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "@tanstack/react-router";
import { ArrowDownUp, PackageOpen, ShoppingBag, SlidersHorizontal } from "lucide-react";
import { useWishlist } from "@/hooks/use-wishlist";
import { toggleWishlist } from "@/lib/wishlist";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { WishlistToggle } from "@/components/ui/wishlist-toggle";
import { Sheet, SheetContent, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import mark from "@/assets/turbo-mark.svg.asset.json";

export type CatalogProduct = {
  id:string; slug:string; name_ar:string; name_en:string|null; is_new:boolean; is_bestseller:boolean;
  category_id:string|null; product_images:{url:string;alt_ar:string;sort_order:number}[];
  product_variants:{id:string;retail_price:number;compare_at_price:number|null;color_name_ar:string;color_value:string|null;size_label:string;sku:string}[];
};

export function useCatalogProducts(){return useQuery({queryKey:["catalog-products"],queryFn:async()=>{const {data,error}=await supabase.from("products").select("id,slug,name_ar,name_en,is_new,is_bestseller,category_id,product_images(url,alt_ar,sort_order),product_variants(id,retail_price,compare_at_price,color_name_ar,color_value,size_label,sku)").eq("status","published").order("created_at",{ascending:false});if(error)throw error;return (data??[]) as CatalogProduct[];}})}
export const money=(n:number)=>new Intl.NumberFormat("ar-EG",{style:"currency",currency:"EGP",maximumFractionDigits:0}).format(n);

export function ProductCard({product,variant="default"}:{product:CatalogProduct;variant?:"default"|"shop"}){
  const { has } = useWishlist();
  const variants=product.product_variants??[]; const prices=variants.map(v=>v.retail_price); const price=prices.length?Math.min(...prices):null;
  const images=[...(product.product_images??[])].sort((a,b)=>a.sort_order-b.sort_order); const image=images[0]; const alternate=images[1];
  const comparePrices=variants.map(v=>v.compare_at_price).filter((value):value is number=>value!==null); const compare=comparePrices.length?Math.max(...comparePrices):null;
  const colors=Array.from(new Map(variants.map(v=>[v.color_name_ar,v.color_name_ar])).values()).slice(0,4);
  const isShop=variant==="shop";
  return <article className="group min-w-0"><div className="relative"><Link to="/products/$slug" params={{slug:product.slug}} className={`relative block aspect-[4/5] overflow-hidden bg-off-white ${isShop?"rounded-sm":"rounded-[10px] border border-border"}`}>
    {image?<><img src={image.url} alt={image.alt_ar} loading="lazy" className="size-full object-cover transition-opacity duration-300 group-hover:opacity-0"/>{alternate&&<img src={alternate.url} alt={alternate.alt_ar} loading="lazy" className="absolute inset-0 size-full object-cover opacity-0 transition-all duration-300 group-hover:scale-[1.02] group-hover:opacity-100"/>}</>:<img src={mark.url} alt="" className="absolute inset-0 m-auto w-1/2 opacity-[.08]"/>}
    {!isShop&&<div className="absolute start-3 top-3 flex flex-wrap gap-2">{product.is_new&&<Badge>جديد</Badge>}{product.is_bestseller&&<Badge variant="secondary">الأكثر طلباً</Badge>}</div>}
  </Link><WishlistToggle pressed={has(product.id)} onPressedChange={async()=>{const wasSaved=has(product.id);try{await toggleWishlist(product.id);toast.success(wasSaved?"اتشالت من المفضلة":"اتضافت للمفضلة")}catch{toast.error("تعذر تحديث المفضلة")}}} className={`absolute end-3 top-3 ${isShop?"size-9 border-border bg-background/85 shadow-none [&_svg]:size-4":""}`}/>{!isShop&&<Button asChild size="sm" className="absolute inset-x-3 bottom-3 hidden opacity-0 transition-opacity duration-200 group-hover:flex group-hover:opacity-100"><Link to="/products/$slug" params={{slug:product.slug}}><ShoppingBag/> اختار المقاس</Link></Button>}</div><div className={isShop?"mt-3":"mt-4"}><Link to="/products/$slug" params={{slug:product.slug}} className="font-semibold transition-colors hover:text-primary">{product.name_ar}</Link><div className={`${isShop?"mt-1":"mt-2"} flex flex-wrap items-center gap-2`}><span className="font-bold">{price===null?"السعر قريباً":money(price)}</span>{compare!==null&&price!==null&&compare>price&&<del className="text-sm text-muted-foreground">{money(compare)}</del>}</div>{!isShop&&colors.length>0&&<p className="mt-2 text-xs text-muted-foreground">{colors.join(" · ")}</p>}</div>
  </article>;
}

type Filters={category:string;size:string;color:string;sort:string};
const initial:Filters={category:"",size:"",color:"",sort:"new"};
type CatalogCategory={id:string;name_ar:string;name_en:string|null;slug:string};
function FilterFields({filters,setFilters,categories,sizes,colors}:{filters:Filters;setFilters:(x:Filters)=>void;categories:CatalogCategory[];sizes:string[];colors:string[]}){return <div className="grid gap-8"><fieldset><legend className="mb-3 text-xs font-bold uppercase text-muted-foreground">Category</legend><div className="grid grid-cols-2 gap-2"><Button size="sm" variant={!filters.category?"default":"outline"} onClick={()=>setFilters({...filters,category:""})}>ALL</Button>{categories.map(c=><Button key={c.id} size="sm" variant={filters.category===c.id?"default":"outline"} onClick={()=>setFilters({...filters,category:c.id})}>{c.name_en?.toUpperCase()||c.name_ar}</Button>)}</div></fieldset><fieldset><legend className="mb-3 text-xs font-bold uppercase text-muted-foreground">Size</legend><div className="flex flex-wrap gap-2"><Button size="sm" variant={!filters.size?"default":"outline"} onClick={()=>setFilters({...filters,size:""})}>ALL</Button>{sizes.map(s=><Button key={s} size="sm" variant={filters.size===s?"default":"outline"} onClick={()=>setFilters({...filters,size:s})}>{s}</Button>)}</div></fieldset><label className="grid gap-3 text-xs font-bold uppercase text-muted-foreground">Color<Select value={filters.color||"all"} onValueChange={value=>setFilters({...filters,color:value==="all"?"":value})}><SelectTrigger className="h-11 rounded-lg bg-background text-foreground"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">ALL COLORS</SelectItem>{colors.map(c=><SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select></label><Button variant="ghost" onClick={()=>setFilters(initial)}>RESET FILTERS</Button></div>}

export function CatalogGrid(){
  const {data=[],isLoading,error}=useCatalogProducts(); const [filters,setFilters]=useState(initial);
  const {data:categories=[]}=useQuery({queryKey:["categories"],queryFn:async()=>{const {data,error}=await supabase.from("categories").select("id,name_ar,name_en,slug").eq("status","published").order("sort_order");if(error)throw error;return data??[];}});
  const sizes=useMemo(()=>Array.from(new Set(data.flatMap(p=>p.product_variants.map(v=>v.size_label)))),[data]);
  const colors=useMemo(()=>Array.from(new Set(data.flatMap(p=>p.product_variants.map(v=>v.color_name_ar)))),[data]);
  const filtered=useMemo(()=>data.filter(p=>(!filters.category||p.category_id===filters.category)&&(!filters.size||p.product_variants.some(v=>v.size_label===filters.size))&&(!filters.color||p.product_variants.some(v=>v.color_name_ar===filters.color))).sort((a,b)=>{const ap=Math.min(...a.product_variants.map(v=>v.retail_price)),bp=Math.min(...b.product_variants.map(v=>v.retail_price));return filters.sort==="low"?ap-bp:filters.sort==="high"?bp-ap:0}),[data,filters]);
  if(isLoading)return <div className="grid grid-cols-2 gap-x-3 gap-y-10 md:grid-cols-3 md:gap-x-6 lg:grid-cols-4"><div className="aspect-[4/5] animate-pulse rounded-sm bg-muted"/><div className="aspect-[4/5] animate-pulse rounded-sm bg-muted"/></div>;
  if(error)return <div className="rounded-[10px] border border-border p-8 text-center"><strong>تعذر تحميل المنتجات.</strong><p className="mt-2 text-sm text-muted-foreground">جرّب تحديث الصفحة بعد قليل.</p></div>;
  const categoryTabs=[{id:"",label:"ALL"},...categories.slice(0,3).map(category=>({id:category.id,label:category.name_en?.toUpperCase()||category.name_ar}))];
  return <><nav aria-label="Product categories" className="-mx-4 overflow-x-auto px-4 [scrollbar-width:none] md:mx-0 md:px-0"><div className="flex min-w-max gap-8 border-b border-border md:gap-12">{categoryTabs.map(category=><button key={category.id||"all"} type="button" onClick={()=>setFilters({...filters,category:category.id})} aria-pressed={filters.category===category.id} className="relative min-h-14 cursor-pointer bg-transparent px-0 text-sm font-bold text-muted-foreground transition-colors hover:text-foreground aria-pressed:text-foreground aria-pressed:after:absolute aria-pressed:after:inset-x-0 aria-pressed:after:bottom-0 aria-pressed:after:h-0.5 aria-pressed:after:bg-primary">{category.label}</button>)}</div></nav><div className="mb-10 mt-6 grid grid-cols-[minmax(0,1fr)_auto] items-center gap-4 border-b border-border pb-6"><span aria-live="polite" className="min-w-0 text-xs font-medium uppercase text-muted-foreground">{filtered.length} PRODUCTS</span><div className="flex shrink-0 items-center gap-2"><Sheet><SheetTrigger asChild><Button variant="ghost" className="px-3"><SlidersHorizontal/> FILTER</Button></SheetTrigger><SheetContent side="right" className="w-[min(92vw,26rem)] overflow-y-auto"><SheetTitle className="text-2xl">FILTER</SheetTitle><div className="mt-10"><FilterFields {...{filters,setFilters,categories,sizes,colors}}/></div></SheetContent></Sheet><div className="relative"><ArrowDownUp aria-hidden="true" className="pointer-events-none absolute start-3 top-1/2 z-10 size-4 -translate-y-1/2"/><Select value={filters.sort} onValueChange={sort=>setFilters({...filters,sort})}><SelectTrigger aria-label="Sort products" className="h-11 w-[7.5rem] rounded-lg border-transparent bg-transparent ps-9 font-bold shadow-none hover:bg-accent"><SelectValue/></SelectTrigger><SelectContent align="end"><SelectItem value="new">NEWEST</SelectItem><SelectItem value="low">PRICE LOW</SelectItem><SelectItem value="high">PRICE HIGH</SelectItem></SelectContent></Select></div></div></div>{filtered.length?<div className="grid grid-cols-2 gap-x-3 gap-y-10 md:grid-cols-3 md:gap-x-6 md:gap-y-14 lg:grid-cols-4">{filtered.map(p=><ProductCard key={p.id} product={p} variant="shop"/>)}</div>:<div className="grid min-h-72 place-items-center text-center"><div><PackageOpen className="mx-auto size-11 text-primary"/><h2 className="mt-4 text-xl font-bold">NO MATCHING PRODUCTS</h2><p className="mt-2 text-muted-foreground">Try changing the filters.</p></div></div>}</>;
}